name: Documentation Issue
description: Report incorrect, outdated, or missing documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Report any issues you find.

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Incorrect information
        - Outdated information
        - Missing information
        - Unclear explanation
        - Broken link
        - Typo/Grammar
        - Code example doesn't work
        - Other
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: Documentation Page
      description: Link to the page with the issue
      placeholder: "https://vesselapi.com/docs/..."
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does it currently say? (Quote or screenshot)
      placeholder: |
        The documentation says:
        "..."
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong?
      description: Explain what's incorrect or missing
      placeholder: |
        This is incorrect because...
        It should say...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How should it be corrected? (If you know)
      placeholder: |
        It should say:
        "..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked that this issue hasn't already been reported
          required: true
